name = "MyStatsPackage"
uuid = "1e42f787-870b-4705-a724-ec9ebe30949b"
authors = ["Nadine Wieters <nadine.wieters@awi.de>"]
version = "0.1.0"

[deps]
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
